### ISSUE TITLE
页面中没有css, javascript的情况下，window.load的时间在DOMContentLoad时间的前面，请问是什么原因？

### ISSUE THREAD

**Issue by rodchen-king** [liangklfangl/react-article-bucket#1]
![default](https://user-images.githubusercontent.com/19780441/37775066-de42e588-2e1c-11e8-88a6-8199f1668357.jpg)

**Comment by liangklfangl** [comment]
可以给我提供个例子，然后一起分析下。最好是个git仓库@rodchen-king

**Comment by rodchen-king** [comment]
https://rodchen-king.github.io/Front-End-performance-optimization/chromePerformence/DOM-empty.html

**Comment by xiangsongtao** [comment]
可能是你页面中插件的音影响

**Comment by rodchen-king** [comment]
ok, 请问你一个在渲染的过程中有一个Update Layer Tree，不太清楚这个的具体的意义是什么？

**Comment by liangklfangl** [comment]
我在[这里面](https://github.com/liangklfangl/react-article-bucket/blob/master/chrome-core/webCore/webkit-render-process.md)有写的
